module.exports = [
    {
        name:"Information",
        struct:{
            username:'String',
            password:'String',
            shopName:'String',
            descibe:'String'
        }
   },
   {
        name:"Shop",
        struct:{
            name:'String',
            descibe:'String',
            image:'String',
            userid:'String'
        }
   }
]